In [1043]:
import tensorflow as tf

In [1044]:
!ls

drive  sample_data


In [1045]:
!pwd


/content


In [1046]:
import numpy as np
import pandas as pd

In [1047]:
train_data=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/train7.csv')
test_data=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/test7.csv')


In [1048]:
train_data.head()

X1  X2  X3  X4  X5  X6  X7  ...   X18   X19   X20   X21   X22   X23  y
0  300000   1   3   2  31   0   0  ...  4000  4000  4100  3300  3500  3500  0
1   20000   1   2   2  24   0   0  ...  1313  2110  4000  6000  4000   174  0
2   90000   2   2   2  35  -1  -1  ...  2667     0     0     0     0     0  0
3  300000   2   2   1  40   1  -2  ...     0     0     0     0     0     0  0
4   70000   2   2   2  36   0   0  ...  3340  2044  1773  1181  1215  1297  1

[5 rows x 24 columns]

In [1049]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
train_data=scaler.fit_transform(train_data)


In [1050]:
x_data=train_data[:,:23]
y_data=train_data[:,23:]
  

In [1051]:
x_data

array([[2.92929293e-01, 0.00000000e+00, 5.00000000e-01, ...,
        5.31400966e-03, 8.20577264e-03, 6.63956460e-03],
       [1.01010101e-02, 0.00000000e+00, 3.33333333e-01, ...,
        9.66183575e-03, 9.37802588e-03, 3.30081211e-04],
       [8.08080808e-02, 1.00000000e+00, 3.33333333e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [4.04040404e-02, 0.00000000e+00, 1.66666667e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [6.06060606e-02, 1.00000000e+00, 3.33333333e-01, ...,
        1.93236715e-03, 0.00000000e+00, 2.27642215e-03],
       [1.51515152e-01, 1.00000000e+00, 3.33333333e-01, ...,
        2.65700483e-03, 3.32919919e-02, 2.84552768e-03]])

In [1052]:
y_data.shape

(22500, 1)

In [1053]:
import keras
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
import tensorflow as tf
from keras.optimizers import SGD  

In [1054]:
x_train,x_test,y_train,y_test = train_test_split(x_data,y_data,test_size = 0.2)

In [1055]:
x_test.shape

(4500, 23)

In [1056]:
y_data[0:5]

array([[0.],
       [0.],
       [0.],
       [0.],
       [1.]])

In [1057]:
model=keras.Sequential([
    keras.layers.Dense(64,activation='relu',input_dim=23),
    keras.layers.Dense(32,activation='relu'),
    keras.layers.Dense(32,activation='relu'),
    keras.layers.Dense(16,activation='relu'),
    keras.layers.Dense(8,activation='relu'),
    keras.layers.Dense(4,activation='relu'),
    keras.layers.Dense(1,activation='sigmoid')
])

In [1058]:
sgd=SGD(lr=0.0099,decay=1e-6)
model.compile(optimizer=sgd,
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [1059]:
model.fit(x_data, y_data, epochs=10, batch_size=32)

Epoch 1/10
704/704 [==============================] - 1s 1ms/step - loss: 0.6052 - accuracy: 0.7646
Epoch 2/10
704/704 [==============================] - 1s 1ms/step - loss: 0.5309 - accuracy: 0.7755
Epoch 3/10
704/704 [==============================] - 1s 1ms/step - loss: 0.5235 - accuracy: 0.7790
Epoch 4/10
704/704 [==============================] - 1s 1ms/step - loss: 0.5214 - accuracy: 0.7768
Epoch 5/10
704/704 [==============================] - 1s 1ms/step - loss: 0.5118 - accuracy: 0.7735
Epoch 6/10
704/704 [==============================] - 1s 1ms/step - loss: 0.4832 - accuracy: 0.7820
Epoch 7/10
704/704 [==============================] - 1s 1ms/step - loss: 0.4682 - accuracy: 0.8035
Epoch 8/10
704/704 [==============================] - 1s 1ms/step - loss: 0.4518 - accuracy: 0.8126
Epoch 9/10
704/704 [==============================] - 1s 1ms/step - loss: 0.4522 - accuracy: 0.8147
Epoch 10/10
704/704 [==============================] - 1s 1ms/step - loss: 0.4504 - accuracy: 0.8150

In [1060]:
test_data.shape

(7500, 23)

In [1061]:
[loss, acc] = model.evaluate(x_test,y_test)

141/141 [==============================] - 0s 964us/step - loss: 0.4468 - accuracy: 0.8169


In [1065]:
test_data=scaler.fit_transform(test_data)


In [1070]:
y_pred=model.predict(test_data)

In [1080]:
(y_pred>0.5).astype('int32')

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0]], dtype=int32)

In [1081]:
np.savetxt('y_pred.csv',y_pred,delimiter=',')